### ISSUE TITLE
other params you can use with i.js ?

### ISSUE THREAD

**Issue by joedockrill** [deepanprabhu/duckduckgo-images-api#11]
hi,

sorry to bother you here but do you know if it's documented anywhere which params i can use with i.js??

i want to be able to restrict searches to square images, certain colors, only photos etc like you can on the ddg gui. i can't find any documentation **anywhere**. where did you originally find it?

**Comment by deepanprabhu** [comment]
Hi @joedockrill ,
Yeah so its an unofficial api, so no documentation.
Most of the code was written through introspection.
I don't have the above features yet, but if you do implement, please share a PR.

**Comment by joedockrill** [comment]
If it's possible to feed those parameters in I certainly will.

**Comment by deepanprabhu** [comment]
Thanks @joedockrill ,
Currently i dont have bandwidth as well, but if i get let me surely include them in the next version.

**Comment by joedockrill** [comment]
Bro,

the param is 'f' and the format is 'size:blah,type:blah,layout:blah,color:blah'
like ',type:photo,layout:Square,color:Monochrome'

See [this notebook](https://github.com/joedockrill/image-scraper/blob/master/ImageScraper.ipynb), duckduckgo_scrape_urls() now takes a bunch of constraint params and there are enums defined just above for all the values which ddg accepts.

**Comment by deepanprabhu** [comment]
Thanks @joedockrill

**Comment by deepanprabhu** [comment]
Would encourage you to submit a PR, @joedockrill .
