### ISSUE TITLE
Your API helped a ton in my project!

### ISSUE THREAD

**Issue by daisyUniverse** [deepanprabhu/duckduckgo-images-api#15]
I just thought I'd drop in and let you know that I adapted this API to work in my project, that is running in python3, here's the commit

https://github.com/robinuniverse/GiveMeOne/commit/67e4d2030fb751eb65b285deda132e4a42850d35

It's heavily modified, but I don't think it would be very hard at all to adapt the full functionality 
Anyways, thanks!

**Comment by deepanprabhu** [comment]
Great to hear that it helped your project, made my day !!

**Comment by deepanprabhu** [comment]
Will check the commit bit later, looking to change the api and add python3 support when i get a chance.

**Comment by deepanprabhu** [comment]
Thank you @robinuniverse
