### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by yam-1111** [deepanprabhu/duckduckgo-images-api#16]
do you have documentations how to use this thanks. Sorry if  lame question

**Comment by deepanprabhu** [comment]
hi @anthonyjohnhinay - Could you check this ? - https://github.com/deepanprabhu/duckduckgo-images-api/blob/master/duckduckgo_images_api/api.py

**Comment by deepanprabhu** [comment]
https://github.com/deepanprabhu/duckduckgo-images-api/blob/master/duckduckgo_images_api/api.py#L84 - line has a sample call - for you to use,
