### ISSUE TITLE
Change for NSFW results

### ISSUE THREAD

**Issue by Runisco** [deepanprabhu/duckduckgo-images-api#4]
I've tried adding 'kp': '-2' to both params, but the results, at least those tested, are always SFW.

**Comment by rachmadaniHaryono** [comment]
it is not `kp` but `p`. to check it see GET json response when you load the next page of ddg image.

**Comment by Runisco** [comment]
Then i've tried changing the p value from 2, to 1, 0, -1 and -2. I see no difference in results.

**Comment by rachmadaniHaryono** [comment]
@Runisco can you search ddg image and see the what is the url for next page?

it would similar to this

>https://duckduckgo.com/i.js?q={nsfw_query}&o=json&p=1&s=50&u=yahoo&f=,,,&l=wt-wt&vqd={random_number}

**Comment by rachmadaniHaryono** [comment]
it match with mine, when i set filter mode in moderate. 

so imo it should have effect when you set the correct `p` value.

if it is not, i recommend enable logging on your code to make sure you send the correct url
