### ISSUE TITLE
Response returned from DDG is not a JSON

### ISSUE THREAD

**Issue by Atom-101** [deepanprabhu/duckduckgo-images-api#8]
The text field of the response variable res has some binary garbage value. It was throwing a JSON Decode Error. On inspecting the res variable, I am getting Content-Type as 'application/x-javascript', so something is wrong. Has DDG search changed, making the script unusable?

**Comment by deepanprabhu** [comment]
can you test again @Atom-101 , I have rolled out a fix.

**Comment by Atom-101** [comment]
It's working now. Thanks :smiley:
